apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-deployment
  labels:
    app: sinatra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sinatra
  template:
    metadata:
      labels:
        app: sinatra
    spec:
      containers:
      - name: sinatra
        image: anraj/hello-synatra:latest
        ports:
        - containerPort: 4567
